color0 #46464c
color1 #ffb4ab
color2 #c2c5da
color3 #c6c6cf
color4 #dabfcf
color5 #c2c5da
color6 #c6c6cf
color7 #e5e2e3
color8 #909097
color9 #ffb4ab
color10 #c2c5da
color11 #c6c6cf
color12 #dabfcf
color13 #c2c5da
color14 #c6c6cf
color15 #e5e2e3

cursor                #e5e2e3
cursor_text_color     #000000
background            #000000
foreground            #e5e2e3
selection_foreground  #c7c6cd
selection_background  #46464c
active_border_color   #c2c5da
inactive_border_color #39393e
url_color             #c2c5da

active_tab_foreground   #2c3040
active_tab_background   #c2c5da
inactive_tab_foreground #c7c6cd
inactive_tab_background #39393e
cursor_trail_color      #c7c6cd
