color0 #46464d
color1 #ffb4ab
color2 #c0c5e1
color3 #c5c6d2
color4 #dfbdd4
color5 #c0c5e1
color6 #c5c6d2
color7 #e5e2e4
color8 #909097
color9 #ffb4ab
color10 #c0c5e1
color11 #c5c6d2
color12 #dfbdd4
color13 #c0c5e1
color14 #c5c6d2
color15 #e5e2e4

cursor                #e5e2e4
cursor_text_color     #000000
background            #000000
foreground            #e5e2e4
selection_foreground  #c6c6cd
selection_background  #46464d
active_border_color   #c0c5e1
inactive_border_color #38393f
url_color             #c0c5e1

active_tab_foreground   #293045
active_tab_background   #c0c5e1
inactive_tab_foreground #c6c6cd
inactive_tab_background #38393f
cursor_trail_color      #c6c6cd
