

background_opacity 0.75

dynamic_background_opacity yes

font_family  JetBrainsMono Nerd Font
font_size    14


#cursor
cursor_trail 1
cursor_trail_decay 0.1 0.4

include themes/noctalia.conf

cursor_shape block
shell_integration no-cursor
